{{- if .Values.openshift -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    description: OpenShift route for application's http service
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  {{- if .Values.route.hostname -}}
  host: {{ .Values.route.hostname }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
{{- end }}
